name: generate pacman game

on:
  # Lance l'action automatiquement toutes les 24h
  schedule:
    - cron: "0 0 * * *"
  
  # Permet de lancer l'action manuellement
  workflow_dispatch:
  
  # Lance l'action à chaque modification sur la branche main
  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # 1. Récupère ton code
      - uses: actions/checkout@v3

      # 2. Génère le Pacman
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # 3. Crée le dossier dist et déplace le fichier dedans (C'est l'étape clé !)
      - name: Move file to dist
        run: |
          mkdir -p dist
          mv pacman-contribution-graph.svg dist/
          mv pacman-contribution-graph-dark.svg dist/ || true

      # 4. Envoie le dossier dist vers la branche "output"
      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
