name: generate pacman game

on:
  # Lance l'action automatiquement toutes les 24h
  schedule:
    - cron: "0 0 * * *"
  
  # Permet de lancer l'action manuellement
  workflow_dispatch:
  
  # Lance l'action à chaque modification sur la branche main
  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
        env:
          # AJOUT IMPORTANT : Le token pour lire tes stats
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify file existence
        run: |
          ls -la
          # Cette commande va lister les fichiers pour voir si le SVG est là

      - name: Move file to dist
        run: |
          mkdir -p dist
          # On déplace le fichier seulement s'il existe pour éviter l'erreur
          if [ -f "pacman-contribution-graph.svg" ]; then
            mv pacman-contribution-graph.svg dist/
          fi
          if [ -f "pacman-contribution-graph-dark.svg" ]; then
            mv pacman-contribution-graph-dark.svg dist/
          fi

      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
